name: flutter_app
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # your existing deps
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^3.1.1
  http: ^1.2.2
  geolocator: ^14.0.2
  image_picker: ^1.0.7
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2

  # camera + tflite (NO helper pkg)
  camera: ^0.11.0
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  collection: ^1.18.0
  file_picker: ^10.3.3
  video_player: ^2.10.0
  permission_handler: ^11.3.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/

