name: Flutter Security & Analysis

on:
  push:
    branches: [ "your-feature-branch" ]
  pull_request:
    branches: [ "your-feature-branch" ]

jobs:
  flutter-analyze-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Check dependencies (non-blocking)
      run: flutter pub outdated || true

    - name: Run Flutter analyze
      run: flutter analyze

